import {test,expect} from '@playwright/test';
import {searchFeatures} from '../src/features/smartfarm/farmUtils.js';
const fixture={settings:{mode:'AUTO',pumpStatus:'OFF',soilThreshold:40,airThreshold:50,tempThreshold:35,lightThreshold:80},sensor:{_id:'sensor-1',soilHumidity:37,airHumidity:63,temperature:29,lightIntensity:72,waterLevel:81,createdAt:'2026-09-07T02:00:00Z'}};
async function setup(page,{logsFail=false,settingsFail=false}={}){
 const state={settings:{...fixture.settings},writes:[],chats:[],settingsFail};
 await page.addInitScript(()=>{localStorage.setItem('token','browser-test-only');localStorage.setItem('user',JSON.stringify({username:'Người kiểm thử',email:'test@example.test'}));});
 await page.route('**/api/farm/**',async route=>{
  const req=route.request(),url=new URL(req.url());let data;
  if(url.pathname.endsWith('/settings')){
   if(state.settingsFail)return route.fulfill({status:503,json:{success:false,message:'Không kết nối được cơ sở dữ liệu.'}});
   if(req.method()==='PUT'){const body=req.postDataJSON();state.writes.push(body);state.settings={...state.settings,...body};}
   data=state.settings;
  }else if(url.pathname.endsWith('/pump/control')){const body=req.postDataJSON();state.writes.push(body);state.settings.pumpStatus=body.action;return route.fulfill({json:{success:true,pumpStatus:body.action}});}
  else if(url.pathname.endsWith('/sensors/latest'))data=fixture.sensor;
  else if(url.pathname.endsWith('/sensors/history'))data=[fixture.sensor,{...fixture.sensor,_id:'sensor-2',soilHumidity:45,createdAt:'2026-09-07T03:00:00Z'}];
  else if(url.pathname.endsWith('/logs')){
   if(logsFail)return route.fulfill({status:500,json:{success:false,message:'Không tải được nhật ký.'}});
   data=Array.from({length:7},(_,i)=>({_id:String(i),createdAt:'2026-09-07T02:00:00Z',startTime:'09:00',endTime:'09:01',duration:'60 giây',humidityBefore:'37%',mode:i===0?'MANUAL':'AUTO',reason:'Kiểm thử nhật ký'}));
  }
  return route.fulfill({json:{success:true,data}});
 });
 await page.route('**/api/chatbot/ask',async route=>{state.chats.push(route.request().postDataJSON());return route.fulfill({json:{success:true,reply:'Cần kiểm tra độ ẩm đất và rễ cây cà chua.'}});});
 return state;
}
test('search matches accents, keywords and multiple words',()=>{expect(searchFeatures('dieu khien')[0].path).toBe('/control');expect(searchFeatures('máy bơm')[0].path).toBe('/control');expect(searchFeatures('DO AM').some(r=>r.path==='/')).toBeTruthy();expect(searchFeatures('   ')).toEqual([]);expect(searchFeatures('xyzxyz')).toEqual([]);});
test('search opens visible results, Enter navigates and clears query',async({page})=>{await setup(page);await page.goto('/');const input=page.getByRole('combobox',{name:'Tìm chức năng'});await input.fill('may bom');await expect(page.getByRole('option',{name:/Điều khiển máy bơm/})).toBeVisible();await input.press('Enter');await expect(page).toHaveURL(/\/control$/);await expect(input).toHaveValue('');await input.fill('khongtimthay');await expect(page.getByText('Không có chức năng phù hợp.',{exact:false})).toBeVisible();await input.press('Escape');await expect(page.getByRole('listbox')).toBeHidden();});
test('dashboard renders measured API values even when logs endpoint fails',async({page})=>{await setup(page,{logsFail:true});await page.goto('/');await expect(page.locator('.huge')).toHaveText('37%');await expect(page.getByText('29°C',{exact:true})).toBeVisible();await expect(page.getByText('81%',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0);});
test('manual, pump, thresholds and reset use correct backend payloads',async({page})=>{const state=await setup(page,{logsFail:true});await page.goto('/control');await page.getByRole('button',{name:/Thủ công \(MANUAL\)/}).click();expect(state.settings.mode).toBe('MANUAL');await page.getByRole('button',{name:'Bật hoặc tắt máy bơm'}).click();expect(state.settings.pumpStatus).toBe('ON');await page.getByRole('button',{name:'Bật hoặc tắt máy bơm'}).click();expect(state.settings.pumpStatus).toBe('OFF');await page.getByRole('slider',{name:'Ngưỡng bật bơm (Độ ẩm đất thấp)',exact:true}).fill('47');await page.getByRole('button',{name:'Lưu cấu hình ngưỡng'}).click();expect(state.settings.soilThreshold).toBe(47);expect(state.writes.at(-1)).not.toHaveProperty('mode');await page.getByRole('button',{name:'Khôi phục mặc định'}).click();await expect(page.getByRole('slider',{name:'Ngưỡng bật bơm (Độ ẩm đất thấp)',exact:true})).toHaveValue('40');expect(state.settings.soilThreshold).toBe(47);});
test('failed settings load can recover with retry',async({page})=>{const state=await setup(page,{settingsFail:true});await page.goto('/control');await expect(page.getByRole('button',{name:/Thủ công \(MANUAL\)/})).toBeDisabled();state.settingsFail=false;await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('button',{name:/Thủ công \(MANUAL\)/})).toBeEnabled();});
test('history filter, page controls and detail work with loaded logs',async({page})=>{await setup(page);await page.goto('/history');await expect(page.locator('tbody tr')).toHaveCount(5);await page.getByRole('button',{name:'›',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(2);await page.getByLabel('Lọc chế độ').selectOption('MANUAL');await expect(page.locator('tbody tr')).toHaveCount(1);await page.getByRole('button',{name:'Xem',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Đóng',exact:true}).click();await page.getByLabel('Lọc theo ngày').fill('2026-09-08');await expect(page.getByText('Chưa có lịch sử phù hợp với bộ lọc.')).toBeVisible();});
test('chat sends typed question, renders backend reply and includes history',async({page})=>{const state=await setup(page);await page.goto('/chatbot');await page.getByLabel('Nội dung hỏi AI').fill('Cây cà chua bị vàng lá?');await page.getByRole('button',{name:'Gửi câu hỏi',exact:true}).click();await expect(page.getByText('Cần kiểm tra độ ẩm đất và rễ cây cà chua.',{exact:true})).toBeVisible();expect(state.chats).toHaveLength(1);expect(state.chats[0].message).toBe('Cây cà chua bị vàng lá?');await page.getByLabel('Nội dung hỏi AI').fill('Nên tưới bao nhiêu?');await page.getByRole('button',{name:'Gửi câu hỏi',exact:true}).click();await expect.poll(()=>state.chats.length).toBe(2);expect(state.chats[1].history.some(m=>m.text==='Cây cà chua bị vàng lá?')).toBeTruthy();});
test('chat API error is visible and retry recovers',async({page})=>{await setup(page);let failed=true;await page.route('**/api/chatbot/ask',route=>route.fulfill(failed?{status:503,json:{success:false,message:'AI đang bận.'}}:{json:{success:true,reply:'Hãy kiểm tra đất trồng.'}}));await page.goto('/chatbot');await page.getByLabel('Nội dung hỏi AI').fill('Đất trồng cây cà chua?');await page.getByRole('button',{name:'Gửi câu hỏi',exact:true}).click();await expect(page.getByText('AI đang bận.')).toBeVisible();failed=false;await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Hãy kiểm tra đất trồng.')).toBeVisible();await expect(page.locator('.message.user')).toHaveCount(1);});
test('settings persist display name and export actual returned logs',async({page})=>{await setup(page);await page.goto('/settings');await page.getByLabel('Tên hiển thị trên thiết bị').fill('Vườn nhà');await page.getByRole('button',{name:'Lưu tùy chọn'}).click();await expect(page.locator('.profile b')).toHaveText('Vườn nhà');await page.getByRole('button',{name:'Tối',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-farm-theme','dark');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Xuất dữ liệu',exact:true}).click();expect((await download).suggestedFilename()).toBe('smartfarm-lich-su.csv');});
test('support search and FAQ expand',async({page})=>{await setup(page);await page.goto('/support');await page.getByLabel('Tìm câu hỏi').fill('ngưỡng');await page.getByText('Cách cài đặt ngưỡng độ ẩm?',{exact:true}).click();await expect(page.locator('details[open]')).toContainText('Lưu cấu hình ngưỡng');});
test('mobile navigation does not overflow viewport',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Mở menu'}).click();await page.getByRole('link',{name:'Điều khiển',exact:true}).click();await expect(page).toHaveURL(/\/control$/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();});
